import type { ThreadItemData } from "./ThreadListItem";

/** Figma node_1805-217021 示例データ */
export const defaultThreadItems: ThreadItemData[] = [
  {
    id: "1",
    unread: true,
    from: "小李",
    receivers: ["自分"],
    hasCc: true,
    threadCount: 100,
    hasAttachment: true,
    subject: "有新的会议需要你参加",
    labels: [
      { id: "l1", text: "会议", colorKey: "primary" },
      { id: "l2", text: "紧急", colorKey: "error" },
    ],
    date: "2023/02/23",
  },
  {
    id: "2",
    unread: true,
    isDraft: true,
    from: "小张",
    receivers: ["自分"],
    threadCount: 10,
    hasAttachment: true,
    subject: "需要你确认一下第三季度的预算计划",
    labels: [{ id: "l3", text: "確認済", colorKey: "success" }],
    date: "2023/02/23",
  },
  {
    id: "3",
    unread: true,
    isDraft: true,
    from: "小王",
    receivers: ["自分"],
    hasCc: true,
    threadCount: 100,
    hasAttachment: true,
    subject: "项目进度报告：Phase 2 completed",
    labels: [{ id: "l4", text: "転送", colorKey: "info" }],
    date: "2023/02/23",
  },
  {
    id: "4",
    flagged: true,
    isDraft: true,
    from: "小赵",
    receivers: ["自分"],
    threadCount: 100,
    hasAttachment: true,
    subject: "下周的会议议程",
    labels: [
      { id: "l5", text: "需要处理", colorKey: "primary" },
      { id: "l6", text: "会议", colorKey: "warning" },
    ],
    date: "2023/02/23",
  },
  {
    id: "5",
    from: "中村 さおり",
    threadCount: 5,
    subject: "关于年度计划制定，请提出你的意见",
    date: "2023/02/22",
  },
  {
    id: "6",
    from: "小孙",
    receivers: ["自分"],
    hasAttachment: true,
    subject: "请确认附件资料：设计书 ver.3",
    date: "2023/02/22",
  },
];
