import type { ThreadItemData } from "./ThreadListItem";

/** Figma node_1805-217021 示例データ */
export const defaultThreadItems: ThreadItemData[] = [
  {
    id: "1",
    unread: true,
    from: "佐藤 孝太郎",
    receivers: ["自分"],
    hasCc: true,
    threadCount: 100,
    hasAttachment: true,
    subject: "新規顧客との取引について：企画部エリア別全体会議のお知らせ",
    labels: [
      { id: "l1", text: "要対応", colorKey: "primary" },
      { id: "l2", text: "緊急", colorKey: "error" },
    ],
    date: "2023/02/23",
  },
  {
    id: "2",
    unread: true,
    isDraft: true,
    from: "鈴木 一郎",
    receivers: ["自分"],
    threadCount: 10,
    hasAttachment: true,
    subject: "【確認依頼】第3四半期の予算計画について確認をお願いします",
    labels: [{ id: "l3", text: "確認済", colorKey: "success" }],
    date: "2023/02/23",
  },
  {
    id: "3",
    unread: true,
    isDraft: true,
    from: "田中 美咲",
    receivers: ["自分"],
    hasCc: true,
    threadCount: 100,
    hasAttachment: true,
    subject: "プロジェクト進捗報告：フェーズ2の完了について",
    labels: [{ id: "l4", text: "転送", colorKey: "info" }],
    date: "2023/02/23",
  },
  {
    id: "4",
    flagged: true,
    isDraft: true,
    from: "山田 健太",
    receivers: ["自分"],
    threadCount: 100,
    hasAttachment: true,
    subject: "来週のミーティングアジェンダについて",
    labels: [
      { id: "l5", text: "要対応", colorKey: "primary" },
      { id: "l6", text: "会議", colorKey: "warning" },
    ],
    date: "2023/02/23",
  },
  {
    id: "5",
    from: "中村 さおり",
    threadCount: 5,
    subject: "年間計画策定の件：ご意見をお聞かせください",
    date: "2023/02/22",
  },
  {
    id: "6",
    from: "小林 大輔",
    receivers: ["自分"],
    hasAttachment: true,
    subject: "添付資料の確認をお願いします：設計書 ver.3",
    date: "2023/02/22",
  },
];
